In [2]:
import numpy as np
import pandas as pd
import h5py
import matplotlib.pyplot as plt

In [3]:
import sys
sys.path.append('/home/vadilloj/MAP2023/Vadillo-Justice-League-Code')

In [17]:
from Runnable_Modules import Base as base, TrackingUtils as tracking

In [15]:
simulations = base.get_chars("sims")

In [14]:
simulations

NameError: name 'simulations' is not defined

In [8]:
s, h1, h = base.load_in_sim("Sandra", return_h = True)

In [10]:

tracked_filepath = "/home/christenc/Code/python/Justice_League_Code/Data/tracked_particles.hdf5"
tracked_particles = pd.read_hdf(tracked_filepath, key = halo)

NameError: name 'halo' is not defined

In [20]:
simulations.at['Sandra', 'Halo keys']

[np.str_('h148_2'),
 np.str_('h148_3'),
 np.str_('h148_4'),
 np.str_('h148_6'),
 np.str_('h148_7'),
 np.str_('h148_10'),
 np.str_('h148_12'),
 np.str_('h148_23'),
 np.str_('h148_27'),
 np.str_('h148_34'),
 np.str_('h148_38'),
 np.str_('h148_55'),
 np.str_('h148_65'),
 np.str_('h148_249'),
 np.str_('h148_251'),
 np.str_('h148_282')]

In [23]:
Hchars_path = '/home/vadilloj/MAP2023/Vadillo-Justice-League-Code/All_halo_charachteristics.csv'
HChars = pd.read_csv(Hchars_path, index_col = 0)
HChars

,time,mstar,mgas,mass,Rvir,x,y,z,Hdist,sfr,t_infall,HI_mass,OVI_mass,host_mass_frac,host_HI_frac,host_OVI_frac,M_inhalo,HI_inhalo,OVI_inhalo
key,,,,,,,,,,,,,,,,,,,
h148_2,13.800797,2.268773e+09,8.252345e+09,9.575866e+10,95.462198,-59.60,-162.55,78.24,189.99,0.476290,NaN,3.166450e+09,2.951845e+04,0.069372,0.224568,0.045517,0.778978,9.970521e-01,2.485345e-01
h148_3,NaN,1.502171e+09,2.975036e+09,4.697010e+10,76.483584,236.62,48.30,114.24,267.16,NaN,NaN,1.027898e+09,1.106206e+04,0.018130,0.040023,0.018883,1.074575,1.816059e+00,2.245034e-01
h148_4,13.800797,4.317847e+08,9.706413e+08,3.248971e+10,67.335904,65.83,-236.64,6.32,245.71,0.025735,NaN,3.577707e+08,1.630198e+03,0.009046,0.025346,0.007483,0.702660,9.981530e-01,8.349161e-02
h148_6,13.800797,3.315968e+08,1.010160e+09,2.869601e+10,64.716224,280.59,-104.37,-129.01,325.99,0.037392,NaN,3.569206e+08,1.589113e+03,0.004255,0.000749,0.003830,1.554449,3.371363e+01,1.590088e-01
h148_10,13.800797,1.353274e+08,1.139460e+09,1.055766e+10,46.469675,-24.02,-133.76,-5.92,136.03,0.022669,NaN,4.378722e+08,1.161519e+02,0.013847,0.035053,0.006264,0.538852,8.833165e-01,7.106595e-03
h148_12,13.800797,1.043767e+08,7.503453e+06,9.071870e+09,43.979036,42.64,281.50,-2.79,284.73,0.000137,NaN,3.043587e+05,8.613388e+01,0.000929,0.001414,0.001445,0.052891,1.522334e-02,2.284602e-02
h148_27,13.800797,8.415728e+07,1.026774e+08,3.249352e+09,31.367917,237.78,147.66,-94.98,295.57,0.000535,NaN,2.159628e+07,2.503571e+01,0.005458,0.006517,0.008144,0.123195,2.343291e-01,1.178148e-03
h148_34,13.800797,5.759679e+06,5.869542e+07,2.628660e+09,29.130301,-296.06,-315.65,-241.34,495.51,0.000000,NaN,6.332316e+06,1.688300e+02,0.000690,0.000282,0.000417,0.556970,1.586624e+00,1.552734e-01
h148_38,13.800797,1.374093e+07,0.000000e+00,1.883522e+09,26.060232,2.87,48.18,-181.80,188.10,0.000000,NaN,0.000000e+00,0.000000e+00,0.000981,0.000951,0.001479,0.000000,0.000000e+00,0.000000e+00
h148_55,13.800797,2.822993e+06,5.263210e+06,1.361924e+09,23.525588,-71.52,14.26,33.44,80.23,0.000000,NaN,1.317506e+06,0.000000e+00,0.001582,0.001107,0.002223,0.021787,8.419661e-02,0.000000e+00
h148_65,13.800797,3.001293e+07,0.000000e+00,8.996108e+08,20.341280,-33.33,-76.81,83.05,117.92,0.000000,NaN,0.000000e+00,0.000000e+00,0.000499,0.000794,0.000972,0.000000,0.000000e+00,0.000000e+00
h148_251,13.800797,2.149496e+06,0.000000e+00,1.815621e+08,11.952184,197.98,6.38,-219.66,295.78,0.000000,NaN,0.000000e+00,0.000000e+00,0.000280,0.000673,0.000846,0.000000,0.000000e+00,0.000000e+00
h148_249,13.800797,2.063790e+06,0.000000e+00,1.861386e+08,12.084551,29.14,180.63,10.97,183.29,0.000000,NaN,0.000000e+00,0.000000e+00,0.000692,0.001447,0.001075,0.000000,0.000000e+00,0.000000e+00
h148_282,13.800797,3.984286e+06,0.000000e+00,1.495318e+08,11.235650,112.71,128.88,60.19,181.49,0.000000,NaN,0.000000e+00,0.000000e+00,0.000207,0.000477,0.000522,0.000000,0.000000e+00,0.000000e+00
h229_14,13.800797,3.338275e+06,2.703543e+07,2.403511e+09,28.258460,257.66,301.63,-53.13,400.24,0.000000,NaN,2.421080e+06,9.500366e+01,0.000651,0.000245,0.000971,0.539821,5.312464e-01,6.970784e-02
h229_18,13.800797,7.714878e+07,0.000000e+00,1.509991e+09,24.209733,20.23,43.32,128.95,137.53,0.000000,NaN,0.000000e+00,0.000000e+00,0.003526,0.005233,0.004190,0.000000,0.000000e+00,0.000000e+00
h229_20,13.800797,8.610682e+05,6.519790e+05,2.025912e+09,26.697664,-7.16,200.96,-183.88,272.48,0.000000,NaN,6.455090e+02,1.334474e+00,0.000332,0.000075,0.000387,0.025534,4.622822e-04,2.459367e-03
h229_22,13.800797,4.786508e+06,0.000000e+00,1.551642e+09,24.447656,-27.96,-38.13,-219.32,224.36,0.000000,NaN,0.000000e+00,0.000000e+00,0.000404,0.000250,0.000646,0.000000,0.000000e+00,0.000000e+00
h229_49,13.800797,6.790767e+06,0.000000e+00,7.641975e+08,19.306726,7.39,-109.24,-11.25,110.06,0.000000,NaN,0.000000e+00,0.000000e+00,0.000750,0.000637,0.000524,0.000000,0.000000e+00,0.000000e+00
h242_8,13.800797,0.000000e+00,2.916159e+05,5.397006e+12,2524.255371,2618.05,-5147.36,-1756.73,6036.19,0.034354,NaN,1.008922e-02,2.359862e-10,0.042365,0.053616,0.033327,0.000075,8.700136e-12,6.126794e-15
h242_10,13.800797,2.477138e+08,2.276692e+09,1.211725e+11,14901.587088,578.01,-945.70,-335.24,1157.94,0.009396,NaN,2.710142e+08,4.157601e+04,0.046579,0.056213,0.045138,0.533666,2.229021e-01,7.969718e-01
h242_21,13.800797,0.000000e+00,0.000000e+00,1.139806e+12,29062.027289,-4040.41,2166.01,6379.09,7855.53,0.000000,NaN,0.000000e+00,0.000000e+00,0.002215,0.000304,0.004424,0.000000,0.000000e+00,0.000000e+00
h242_30,13.800797,5.322599e+07,1.453714e+09,7.091480e+09,24867.343522,-20494.08,-13965.20,-1154.72,24826.75,0.000000,NaN,7.356529e+08,6.335230e-04,0.000724,0.000923,0.000627,21.916692,3.685118e+01,8.742064e-07
h242_38,13.800797,0.000000e+00,0.000000e+00,7.776950e+09,17343.015297,-4648.07,-17372.41,-2285.26,18128.09,0.000000,NaN,0.000000e+00,0.000000e+00,0.000466,0.000075,0.000423,0.000000,0.000000e+00,0.000000e+00
h242_69,13.800797,1.149230e+07,4.381391e+07,9.322223e+09,23912.836453,-5233.07,-18227.97,15780.35,24671.10,0.000000,NaN,6.489503e+06,9.188295e+02,0.002812,0.002372,0.002153,0.170138,1.264801e-01,3.691732e-01
h242_401,13.800797,0.000000e+00,0.000000e+00,8.967824e+10,32993.649324,2363.01,-11798.80,2783.86,12350.93,0.000000,NaN,0.000000e+00,0.000000e+00,0.000509,0.000661,0.000422,0.000000,0.000000e+00,0.000000e+00
h329_7,13.800797,2.747402e+07,2.476791e+08,5.129210e+09,32.738173,53.53,-33.41,15.58,64.99,0.001193,NaN,6.756492e+07,4.063190e-02,0.017682,0.111979,0.002594,0.524004,9.712702e-01,2.060643e-05
h329_29,13.800797,1.491121e+06,0.000000e+00,1.403478e+09,23.658594,-240.56,-506.82,113.85,572.45,0.000000,NaN,0.000000e+00,0.000000e+00,0.001573,0.001954,0.001923,0.000000,0.000000e+00,0.000000e+00
h329_117,13.800797,3.084173e+06,0.000000e+00,2.398850e+08,13.075619,52.26,59.03,-81.65,113.50,0.000000,NaN,0.000000e+00,0.000000e+00,0.000062,0.000077,0.000078,0.000000,0.000000e+00,0.000000e+00

In [19]:
tracking.find_halo_keys(simulations)

()

,gal num,filepath,Halo keys,mass,mstar,mgas,Rvir,nSats,HI_mass,OVI_mass,sat_mass_frac,sat_HI_frac,sat_OVI_frac
Sandra,h148,/home/vadilloj/MAP2023/Sims/h148.cosmo50PLK.30...,"[h148_2, h148_3, h148_4, h148_6, h148_7, h148_...",2.052077e+12,1.917510e+11,1.527100e+11,266.215150,16.0,1.414185e+10,2.609339e+06,0.009316,0.337959,0.098410
Ruth,h229,/home/vadilloj/MAP2023/Sims/h229.cosmo50PLK.30...,"[h229_14, h229_18, h229_20, h229_22, h229_49]",1.052426e+12,1.020237e+11,7.695528e+10,214.442995,5.0,1.862303e+10,1.403408e+06,0.000414,0.006439,0.006718
Sonia,h242,/home/vadilloj/MAP2023/Sims/h242.cosmo50PLK.30...,"[h242_8, h242_10, h242_21, h242_30, h242_38, h...",1.150238e+12,8.973881e+10,9.158841e+10,275.603382,7.0,2.162918e+10,1.155743e+06,0.007511,0.112475,0.085670
Elena,h329,/home/vadilloj/MAP2023/Sims/h329.cosmo50PLK.30...,"[h329_7, h329_29, h329_117]",7.104449e+11,8.991782e+10,2.673112e+10,188.010756,3.0,6.212192e+08,7.602241e+05,0.000727,0.114009,0.004595